"""`results/day7/day7.md`, generated from the JSON the harnesses wrote.

Nothing here is hand-edited, for the reason Day 6 Phase 1 found the hard way:
`results/day5/retrieval.md` was a generated document whose generator carried
`122` as a literal, so re-verifying the golden set silently made a *published*
document wrong. Every number below is read from the file that measured it, and a
missing key is an error rather than a default.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEAD = """# Day 7 — multi-agent, measured

Generated by `python -m regops_agents.report`. Do not edit by hand.

Model: `{model}` · fan-out width {width} · {repeats} timing rounds
"""


def _fanout(d: dict) -> str:
    s = d["summary"]
    return f"""
## Did parallel fan-out buy anything?

Four independent sub-agents over four documents — one context window each, no
shared intermediate. Measured **inside the graph**, arms alternating, median of
{d["repeats"]} rounds. `OLLAMA_NUM_PARALLEL` {d["ollama_num_parallel"]}.

| | seconds |
|---|---|
| sequential (median) | **{s["sequential_median_s"]:.2f}** |
| parallel (median) | **{s["parallel_median_s"]:.2f}** |
| speedup | **{s["speedup"]:.2f}×** |
| ceiling, `sum / max` | {s["ceiling"]:.2f}× |
| share of the available saving captured | {s["captured"]:+.1%} |

**Nothing.** The ceiling says a perfect orchestrator could have won
{s["ceiling"]:.2f}× on this work. **{s["captured"]:+.1%} of it was captured** — the
parallel arm was, if anything, marginally slower.

The reason is the second measurement, and it is the part that transfers to other
hardware: one branch is **{s["queued_fraction"]:.0%} queued model time**
({s["model_s_total"]:.2f}s across four branches) and
{1 - s["queued_fraction"]:.0%} uncontended MCP and DuckDB work
({s["read_s_total"]:.2f}s). Fan-out earns its keep when the un-queued half is
large. Here the branches are not competing for the orchestrator, they are
queueing at one model server, and adding concurrency in front of a queue does
not shorten it.
"""


def _table(rows: list[dict]) -> str:
    out = [
        "| architecture | completed | steps | p50 s | tokens | $ | citations | "
        "unresolvable | documents judged |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| `{r['architecture']}` | {r['completed']}/{r['n']} | {r['steps_total']} | "
            f"{r['p50_s']:.2f} | {r['tokens']:,} | {r['usd']:.5f} | {r['cited']} | "
            f"{r['unresolvable']} | {r['docs_judged_mean']:.1f} |"
        )
    return "\n".join(out)


def _pct(a: float, b: float) -> str:
    """`a` relative to `b`, as a signed percentage."""
    return f"{(a - b) / b * 100:+.0f}%" if b else "n/a"


def _architectures(d: dict) -> str:
    look = {r["architecture"]: r for r in d["sets"]["lookup"]}
    cov = {r["architecture"]: r for r in d["sets"]["coverage"]}
    s, p, a = look["supervisor"], look["plan_and_execute"], look["single_agent"]
    cs, ca = cov["supervisor"], cov["single_agent"]
    invented = ca["unresolvable"] / max(ca["cited"], 1)

    return f"""
## Three architectures, two task sets

**Lookup** — {a["n"]} golden questions, one clause each. The set Day 6's single
agent was built for.

{_table(d["sets"]["lookup"])}

**Coverage** — {ca["n"]} tasks asking which documents address a topic. One
context window per document, and a verdict per document.

{_table(d["sets"]["coverage"])}

### What the numbers say

**On lookup the supervisor is slower and better, and the margin is small.**
{_pct(s["p50_s"], a["p50_s"])} on p50 latency, {_pct(s["tokens"], a["tokens"])}
on tokens, and {s["cited"] - s["unresolvable"]} resolvable citations against
{a["cited"] - a["unresolvable"]}. A latency tax that size, for citations that can
actually be followed, is a trade most compliance work would take — and it is a
*small* margin, which is the honest way to report it. **If the task is one clause
and nobody is going to check the citation, a single agent is the right
architecture and this graph is overhead.**

**On coverage the single agent does not merely lose, it fails differently.**
{ca["n"] - ca["completed"]} of {ca["n"]} runs hit the step ceiling; it spent
{_pct(ca["tokens"], cs["tokens"])} the tokens; and **{ca["unresolvable"]} of the
{ca["cited"]} identifiers it cited do not exist**. It names more documents
({ca["docs_judged_mean"]:.0f} against {cs["docs_judged_mean"]:.0f}) because it
pastes search results back at you; the supervisor is capped at the fan-out width,
which is a deliberate limit and a real one. **Breadth against verifiability, and
{invented:.0%} of the breadth is invented.**

**Plan-and-execute is the supervisor minus one edge, and it is cheaper.**
{_pct(p["tokens"], s["tokens"])} tokens and {p["steps_total"]} steps against
{s["steps_total"]}, for **identical** citation counts on both sets. The
supervisor's reroute — send the run back to the retriever when a citation fails
or the context did not answer the question — fired on this set and changed no
outcome. It earns its keep only when it fires *and* fixes something, and the
lookup set is not where that happens. That is the case against the more complex
control flow, made with its own numbers.
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dir", type=Path, default=Path("results/day7"))
    ap.add_argument("--out", type=Path, default=Path("results/day7/day7.md"))
    a = ap.parse_args(argv)

    fan = json.loads((a.dir / "fanout.json").read_text())
    arch = json.loads((a.dir / "architectures.json").read_text())

    body = (
        HEAD.format(model=fan["model"], width=fan["width"], repeats=fan["repeats"])
        + _fanout(fan)
        + _architectures(arch)
    )
    a.out.write_text(body.rstrip("\n") + "\n")
    print(f"-> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
